export const SWITCH_THEME = 'SWITCH_THEME';
export const TOGGLE_COLLECT = 'TOGGLE_COLLECT';
export const ADD_COLLECT = 'ADD_COLLECT';
export const REMOVE_COLLECT = 'REMOVE_COLLECT';
export const GET_COLLECT_FROM_LOCAL = 'GET_COLLECT_FROM_LOCAL';

export const REQUEST_SEARCH_VIDEO = 'REQUEST_SEARCH_VIDEO';
export const RECEIVE_SEARCH_VIDEO = 'RECEIVE_SEARCH_VIDEO';
export const RECEIVE_SEARCH_VIDEO_FAIL = 'RECEIVE_SEARCH_VIDEO_FAIL';
